Next.JS setup done
KeManen/Data-Intensive-Project pull request #1
Opened 2023-11-26 10:56 UTC by OttoAhlfors

2023-11-26 10:58 UTC, EddieTheCubeHead requested changes

2023-11-26 10:58 UTC, EddieTheCubeHead commented on client/package-lock.json
Voidaanko gitignoree package-lock?

2023-11-26 11:04 UTC, OttoAhlfors commented on client/package-lock.json
Toki

2023-11-26 11:07 UTC, EddieTheCubeHead commented on client/package-lock.json
Sun pitää vielä poistaa se ja uudelleengeneroida nii git osaa poistaa sen. Git on sillai tyhmä

2023-11-26 11:14 UTC, OttoAhlfors commented on client/package-lock.json
Siis poistaa package-lock tiedosto vai?

2023-11-26 11:15 UTC, EddieTheCubeHead commented on client/package-lock.json
Juu

2023-11-26 11:30 UTC, KeManen approved these changes

2023-11-27 10:36 UTC, EddieTheCubeHead approved these changes

2023-12-03 09:50 UTC, merged